apiVersion: v1
kind: ConfigMap
metadata:
  name: html-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Hello, World, v1!</title>
      </head>
      <body>
        <h1>Hello, World, v1!</h1>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-v2
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Hello, World, v2!</title>
      </head>
      <body>
        <h1>Hello, World, v2!</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ["sleep", "10"]
      containers:
        - name: nginx
          image: nginx:1.15
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: html-v1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
