apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  initContainers:
    - name: init-container-1
      image: busybox:latest
      command: ["sh", "-c", "echo $(date) init-container-1 >> /tmp/foo"]
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    - name: init-container-2
      image: busybox:latest
      command: ["sh", "-c", "echo $(date) init-container-2 >> /tmp/foo"]
      volumeMounts:
      - mountPath: /tmp
        name: tmp
  containers:
    - name: container-1
      image: busybox:latest
      command: ["sh", "-c", "echo $(date) container-1 >> /tmp/foo"]
      volumeMounts:
      - mountPath: /tmp
        name: tmp
    - name: container-2
      image: busybox:latest
      command: ["tail", "-f", "/tmp/foo"]
      lifecycle:
        postStart:
          exec:
            command: ["sh", "-c", "echo $(date) container-2-post-start >> /tmp/foo"]
        preStop:
          exec:
            command: ["sh", "-c", "echo $(date) container-2-pre-stop >> /tmp/foo"]
      volumeMounts:
      - mountPath: /tmp
        name: tmp
  restartPolicy: OnFailure
  volumes:
    - name: tmp
      emptyDir: {}
