apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lobsters-script-mail-new-activity
  labels:
    app: lobsters
    component: script
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: lobsters
            component: rake
        spec:
          containers:
            - name: lobsters
              image: mstrzele/lobsters:latest
              envFrom:
                - secretRef:
                    name: mysql
              env:
                - name: DATABASE_URL
                  value: mysql2://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql/$(MYSQL_DATABASE)
              command: ["bundle"]
              args: ["exec", "ruby", "script/mail_new_activity"]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
